### ISSUE TITLE
buttonText type

### ISSUE THREAD

**Issue by jay-bricksoft** [Mastermindzh/react-cookie-consent#1]
I would like to suggest a change of buttonText proptype.
My application uses react-intl for i18n, which renders components for translatet strings.
I can pass a i18n component as buttonText, which works but creates an error because `object`  doesn't match string type.

My suggest for a fix would be to allow react components as valid proptype for buttonText.

**Comment by Mastermindzh** [comment]
Seems like a solid idea!

In your first commit (allow React-Components as buttonText) you added PropTypes.func rather than PropTypes.element though.

I see you're preparing a pull-request so I'll wait till you finish that and merge the changes :)

**Comment by jay-bricksoft** [comment]
I used proptypes func which covers all types of components, where proptypes.element doesn't cover functional stateless compnents (see https://stackoverflow.com/a/45316411/3793309 )

my changes are ready to merge now.

**Comment by Mastermindzh** [comment]
Hey! I didn't know that! Excellent!

I'll proceed with merging :)

**Comment by jay-bricksoft** [comment]
Thank you for the lightning-fast response !
I'll close this issue when pushed to NPM ;)

**Comment by Mastermindzh** [comment]
No problem man, glad we could improve the product :)

I published it to NPM with version 1.0.5.

Have a nice day!

**Comment by jay-bricksoft** [comment]
Thank you!

**Comment by jay-bricksoft** [comment]
I did a mistake on PropTypes.
will submit a fix in a second.

**Comment by Mastermindzh** [comment]
Done and dusted.  Thanks again man!

Note to self: even something as small as a proptype PR needs te be tested haha

**Comment by jay-bricksoft** [comment]
True! Maybe PRs and current work could live on a separate branch while successful tests merge to master which gets built and distributed. We could discuss this on another issue.

**Comment by jay-bricksoft** [comment]
Still after some testing: proptype checking is too verbose - we need to add proptypes.element

this is hopefully the last fix for this issue
