### ISSUE TITLE
[Question] Design?

### ISSUE THREAD

**Issue by Mistik** [Mastermindzh/react-cookie-consent#100]
Hi

Im trying to make my button for cookie consent appear in the bottom right corner, how can I do this?

Here is an example of what I mean
![image](https://user-images.githubusercontent.com/60430725/100392020-20fc4f80-302d-11eb-948c-cc711d23a39e.png)

**Comment by Mastermindzh** [comment]
Hey @Mistik 

You can overwrite the style in code like so:

```js
<CookieConsent
            style={{
              alignItems: "baseline",
              background: "#353535",
              color: "white",
              display: "block",
              left: "initial",
              right: "0",
              position: "absolute",
              width: "300px",
              zIndex: "999",
              margin: "20px"
            }}
          >
```

This will make the bar display as a sort of toastr in the bottom right:
![image](https://user-images.githubusercontent.com/4190290/100538249-e82bc880-322e-11eb-91ba-0453a1ae953c.png)

I also made a [StackBlitz](https://stackblitz.com/edit/react-cookie-consent-issue-100?file=index.js) :smile: 

You can change more css to get the look you desire, good luck!
