### ISSUE TITLE
Doesn't seem to be a way to easily read cookie status on page reload

### ISSUE THREAD

**Issue by jobeland** [Mastermindzh/react-cookie-consent#103]
This seems to work great on initial page load to prompt the user and save the cookies (modern and legacy), and the onAccept() callback works great to cue off additional initialization work for analytics, but on subsequent page loads, it would be great if this also exported a getCookieValue() functionality so apps would be able to see if it was previously consented and cue actions off of that (like initializing analytics libraries). 

Currently, it seems we need to know the cookie values to look for, and then look for both the modern and legacy values to see if they are set. Since this logic is already encapsulated within the library, it would be great to keep it there and just leverage it.

**Comment by Mastermindzh** [comment]
Quite right there isn't.
Will add it :)

**Comment by Mastermindzh** [comment]
Released in [6.2.0](https://www.npmjs.com/package/react-cookie-consent/v/6.2.0).

Enjoy :smile:

**Comment by jobeland** [comment]
Thanks for the quick turnaround @Mastermindzh. When you get the chance, can you publish the updated TS definition file as well?

**Comment by Mastermindzh** [comment]
Keep forgetting about that thing... will do it tonight.

**Comment by Mastermindzh** [comment]
Released in [6.2.1](https://www.npmjs.com/package/react-cookie-consent/v/6.2.1)
