### ISSUE TITLE
Get warning "Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function."

### ISSUE THREAD

**Issue by rvnash** [Mastermindzh/react-cookie-consent#109]
Whenever I use react-cookie-consent I get this warning when transitioning off the page. Is this perhaps creating state in an useEffect hook that it is not cleaning up?

**Comment by Mastermindzh** [comment]
Hey @rvnash,

This component doesn't use the hooks API at all.
If you can provide a Stackblitz with the minimal amount of code required to replicate the issue I'll have a look anyway 😄

**Comment by rvnash** [comment]
Thanks for responding. I tried to replicate the issue with a minimal react
app, and it did not reproduce the problem. So clearly, the problem is in my
code somewhere. Although, in my more elaborate app where I see the problem,
it goes away simply by removing react-cookie-consent. I'll keep looking,
but for now, I'm afraid I can't pin it down.
- Richard Nash

**Comment by Mastermindzh** [comment]
Ok man, I'll close the issue for now. If you find the problem please post back here as well :)
