### ISSUE TITLE
Ability to require re-consent?

### ISSUE THREAD

**Issue by derykmarl** [Mastermindzh/react-cookie-consent#112]
Just wondering if there's some way to "reset" consent for all previous visitors.  For example, I would like to add some additional tracking to our site, which will also add additional cookies.  Really we should then be asking for fresh consent with the updated cookie notice, because the user chose to accept the list of cookies described to them, not additional ones we added later (hypothetically, this could be done deceptively, which is obviously not our intention)

**Comment by Mastermindzh** [comment]
Hey @derykmarl ,

Due to the nature of cookies you can't "reset/remove" then on the devices of your users.
What you can do, however, is to change the name your cookie bar uses for the cookie.
Your users won't have a cookie with the new name and thus the bar will ask them to accept/deny cookies.


Simply change "cookieName":

```js
<CookieConsent
  cookieName="website-new-policy-cookie"
>
yay
</CookieConsent>
```

**Comment by derykmarl** [comment]
Ah of course... good to know it's easy to change the cookie name.  Thanks!

**Comment by monojones** [comment]
You don't need to change the cookie name. Use the cookie value to store a string value (version), and then check if client matches, otherwise reset. Something like this

`
        const consentedVersion = getCookieConsentValue()
        const cookieConsent = consentedVersion && consentedVersion === __COOKIE_CONSENT_VERSION

        if(consentedVersion && !cookieConsent)    { //the user has an old cookie version, forcing delete
            console.log("cookie consent version renewed: reseting")
            resetCookieConsentValue()
        }
`
