### ISSUE TITLE
Not working anymore on new React version ?

### ISSUE THREAD

**Issue by BenoKop** [Mastermindzh/react-cookie-consent#115]
Hello,

I just installed your cookie consent bar and I'm not able to making it work...
I'm running it on React 17.0.1 and this is the simple code that I tried :
```
<CookieConsent
  onAccept={() => {
	  alert('yay!');
  }}
  enableDeclineButton
  declineButtonText="Decline (optional)"
  onDecline={() => {
	  alert('nay!');
  }}>
  This website uses cookies to enhance the user experience.{' '}
  <span style={{ fontSize: '10px' }}>
	  This bit of text is smaller :O
  </span>
</CookieConsent>
```
without debug, it even doesn't show up in the DOM.

If I use debug true, it is showing up in the DOM but with the class "CookieConsent" which is hidding the bar.
![image](https://user-images.githubusercontent.com/32838942/121703274-f2c6f480-cad2-11eb-9f2b-b28ae0851506.png)

Am i doing something wrong ?

Thanks !

**Comment by Mastermindzh** [comment]
I can't reproduce this with a brand-new `create-react-app` and install of react-cookie-install.

![image](https://user-images.githubusercontent.com/4190290/121707121-8c43d580-cad6-11eb-9d39-f5e41833012f.png)

**Comment by BenoKop** [comment]
mmmh okay, thanks for trying, i'll try to figure it out.

**Comment by BenoKop** [comment]
react-cookie-install, you mean react-cookie-consent ?

**Comment by BenoKop** [comment]
Could you please send your App.js code ?
I'm still getting the issue on a brand new create-react-app :(

**Comment by Mastermindzh** [comment]
Sure can.

Here's the entire project on [filebin](https://filebin.net/anh3zlwdznih8ms0), it will be deleted in 6 days.

It even includes node_modules :)

**Comment by BenoKop** [comment]
filebin seems to be down for the moment...

**Comment by Mastermindzh** [comment]
Let's do it on stackblitz then: https://stackblitz.com/edit/react-ts-frrtpq?file=index.tsx

![image](https://user-images.githubusercontent.com/4190290/121861858-81698a80-ccfa-11eb-8181-b0aa7db0e6bc.png)

**Comment by BenoKop** [comment]
thanks alot

**Comment by Mastermindzh** [comment]
No problem. Hope you can figure it out 😄
