### ISSUE TITLE
onAccept Cookies.set('gatsby-gdpr-google-analytics', 'true'); always have a lifetime of session ! ?

### ISSUE THREAD

**Issue by gindev77** [Mastermindzh/react-cookie-consent#119]
Hello,
As i told in the title of this issue.
Even if i use the props expire={365} inside the <Cookieconsent> component, the max age lifetime of the cookie when i set it to true using the onAccept() method show me the lifetime equal to :  session.
So, this is  a probleme because if the user consent to the cookie, theen leave the site and  come back, the banner will show up again ....
Why this behaviour ?
On the other hand, when i set the cookie to false  or even if i don't set  anything in the onDecline() method, the lifetime is well took in charge with one year lifetime ...

**Comment by Mastermindzh** [comment]
Hey @gindev77 ,

Only cookies set by the component take that expires value into account. Setting cookies manually doesn't.

You can do it like this tho:

```js
Cookies.set('gatsby-gdpr-google-analytics', 'true',{expires:365})
```

**Comment by gindev77** [comment]
Oooo thank you very much Mastermindzh! It's now working perfectly!!!!, ididn't understood that  i could pass each props this way.

**Comment by Mastermindzh** [comment]
No problem @gindev77 ,

Enjoy and have a nice day!
