### ISSUE TITLE
Overlay is visible when cookie blocker is installed

### ISSUE THREAD

**Issue by GiovanniIncammicia** [Mastermindzh/react-cookie-consent#121]
When the user has a cookie blocker installed, the cookie consent div (text+buttons) disappear (as it is supposed to), but the overlay remains, thus making the application impossible to use.

As far as I see from the devtools, cookie blockers work by applying display: none to any div with a bunch of standard classnames (in this case ClassConsent).

Is it possible to give the overlay a recognizable class? It doesn't have one at the moment.

**Comment by Mastermindzh** [comment]
Yep,

The "overlayClasses" parameter is meant to do just that :)

```jsx
<CookieConsent 
   overlayClasses={'whateverMakesTheThingDissappear'}
>
text
</CookieConsent>`

The current default value is "", but we could add one... I've heard multiple class names being used by those blockers though :)
