### ISSUE TITLE
button styling

### ISSUE THREAD

**Issue by sjb3** [Mastermindzh/react-cookie-consent#123]
Hi guys, quick question,

After adding 'enableDeclineButton' and  'declineButtonText',
I wanna add styling to both buttons with borderRadius.

However, my styling to 'buttonStyle' affects only the ACCEPT button but REJECT.
Is there way to style both buttons?

Thanx!

![image](https://user-images.githubusercontent.com/14283946/130142076-2878b3b3-334d-49ce-b565-dbb6be8d46de.png)

**Comment by Mastermindzh** [comment]
Hey @sjb3 ,

The decline button has a separate styling object. The parameter for it is called `declineButtonStyle`.
So to change both buttons you would have to pass both `buttonStyle` and `declineButtonStyle`.

That accept button looks neat tho!

**Comment by sjb3** [comment]
YOU'RE THE BEST!

Thanx!

________________________________
