### ISSUE TITLE
Does this work with with Next.js?

### ISSUE THREAD

**Issue by kamal-choudhary** [Mastermindzh/react-cookie-consent#128]
First of all thanks for this useful package.

I have a static website in Next.js and I have two scripts in it i.e. Google Analytics 4 & TruConversion Heatmap.

Both of these scripts are implemented using the newest next/script component.

When the user loads my website, I want to show the cookies consent banner (Like the one in the README file of this package), if the user accepts then I want my scripts i.e. GA4/Heatmap to run otherwise don't run those scripts.

is this something possible with this package?

**Comment by chiqui3d** [comment]
Well, I see a problem here, `OnAccept` should always run, because once accepted, when navigating to another page I can't add the Google Analytics scripts.

Right now as it is, you will have to repeat the code in another component, there are two options to avoid messing up the code:

1. Add `onInitialise `here I get the cookie value to add the scripts.
2. `OnAccept`, always run on page load.

**Comment by chiqui3d** [comment]
Forget it, with useEffect I fixed it by putting the same function and checking the Cookie, as I have seen in some of your examples.

**Comment by kamal-choudhary** [comment]
Hi @Mastermindzh,

I'm so sorry for the delayed response.

And thank you so much for the help.

Using your library and code snippet, I was able to build the feature I wanted.

I'm posting a short snippet of my code below. So, if someone comes here in the future and needs help, he can use this code.

`_app.js file`

```
import Script from "next/script";
import CookieConsent, { getCookieConsentValue } from "react-cookie-consent";

const App = ({ Component, pageProps }) => {
  const [cookieConsentGiven, setCookieConsentGiven] = useState(
    getCookieConsentValue()
  );

 return (
    <>
          <Layout>   
            <Script
              strategy="lazyOnload"
              src={`https://www.googletagmanager.com/gtag/js?id=GA_ID`}
            />
            <Script id="ga-analytics">{`
                 // Google Analytics code
            `}</Script>

            {(cookieConsentGiven === true || cookieConsentGiven === "true") && (
              <Script id="truconversion-heatmap" strategy="lazyOnload">{`
                  //TruConversion code
              `}</Script>
            )}

            <Component {...pageProps} />

            <CookieConsent
              location="bottom"
              buttonText="Accept Marketing Cookies"
              declineButtonText="Reject Marketing Cookies"
              enableDeclineButton
              expires={365}
              style={{ background: "#2B373B" }}
              buttonStyle={{ color: "#4e503b", fontSize: "13px" }}
              onAccept={() => setCookieConsentGiven(true)}
              onDecline={() => setCookieConsentGiven(false)}
            >
              This website uses cookies. Some are essential, while others help us improve your experience.
            </CookieConsent>
          </Layout>
    </>
  );
};

export default App;
```

P.S: I'm using consent cookies only for TruConversion Heatmap script. The Google Analytics script runs regardless of whether the user accepts/rejects cookies.
