### ISSUE TITLE
Custom attributes

### ISSUE THREAD

**Issue by agnislav** [Mastermindzh/react-cookie-consent#132]
Hi there.

First, many thanks for the plunging. It's straightforward and easy to use.

At the moment the only feature missed is the ability to add custom `data-` attributes for the container, text, and buttons. The reason behind it is using cypress for e2e and using custom `data-cy` attributes for element identification. We use custom components for buttons, so that's not an issue at the moment for us. However, for the container and the text, we are forced to use classes or ids, which breaks consistency. 

Are there any plans on adding this possibility in near future? 

Many thanks!

**Comment by Mastermindzh** [comment]
There weren't, but I can add them this week 😄

**Comment by Mastermindzh** [comment]
Sorry for the long wait...
Version [7.1.0](https://www.npmjs.com/package/react-cookie-consent/v/7.1.0) ships with this feature:

```jsx
      <CookieConsent
        customContainerAttributes={{ "data-cy": "some-custom-attribute" }}
      >
        This website uses cookies to enhance the user experience.{" "}
        <span style={{ fontSize: "10px" }}>This bit of text is smaller :O</span>
      </CookieConsent>
```
![image](https://user-images.githubusercontent.com/4190290/146674965-76a26fe5-5b0b-4dbb-9f3f-5793c85427ed.png)

Enjoy!
