### ISSUE TITLE
button looks in wrong position in android chrome - mobile

### ISSUE THREAD

**Issue by javismiles** [Mastermindzh/react-cookie-consent#133]
This is a great plugin, thank you very much :)
the only issue we have is that on mobile phones, with chrome, on android,
the "I understand" button moves down and to the left, totally misaligned with the text above, how can we at least make it be centered below the text? and even better how can we prevent it from moving down, because even if we shorten the text to: "This site uses cookies", the button still jumps down and to the left on mobile devices, how can we keep it in the same line as text, or at least centered below the text (would be nice to know both), thank you :)

**Comment by Mastermindzh** [comment]
Hey @javismiles ,

Sorry for the late reply :)
You can do this by adding 2 lines of code:

```jsx
 <CookieConsent
	 // this removes the default width of 300 for the text
	 // so the button will always go to the right if it fits
	 contentStyle={{ flex: '1 0 0' }}
	 // this determines what to do if it doesn't fit next to the text, in your case.. center :)
	style={{ justifyContent: 'center' }}
	>
		Cookies!
</CookieConsent>
```

See: [Stackblitz](See: https://stackblitz.com/edit/react-cookie-consent-issue-102-krl26b?file=style.css) for a working example

Enjoy!

**Comment by javismiles** [comment]
@Mastermindzh brilliant help thank you very much, it works :) by the way does your great plugin allow for the user to revoke the consent later on? I have to check the docs, thank you again :)

**Comment by Mastermindzh** [comment]
You can use the exported member `resetCookieConsentValue` to reset the cookie value, the bar will show up again :)
