### ISSUE TITLE
Gatsby production build fails, `WebpackError: ReferenceError: self is not defined`

### ISSUE THREAD

**Issue by sebastiendan** [Mastermindzh/react-cookie-consent#136]
Version: 7.0.0 
(gatsby@4.2.0)

The package is working fine with Gatsby in dev mode, but breaks production build when generating static html files.

```
failed Building static HTML for pages - 2.400s

 ERROR #95313 

Building static HTML failed for path "/"

See our docs page for more info on this error: https://gatsby.dev/debug-html


   8 |     ? (exports.ReactCookieConsent = t())
   9 |     : (e.ReactCookieConsent = t());
> 10 | })(self, function () {
     |  ^
  11 |   return (function () {
  12 |     var e = {
  13 |         808: function (e, t, n) {


  WebpackError: ReferenceError: self is not defined
  
  - index.js:10 
    [website-corporate]/[react-cookie-consent]/build/index.js:10:2
  
  - bootstrap:19 
    website-corporate/webpack/bootstrap:19:1
  
  - CookieConsent.tsx:17 
    website-corporate/src/components/CookieConsent.tsx:17:15
  
  - bootstrap:19 
    website-corporate/webpack/bootstrap:19:1
  
  - index.js:75 
    [website-corporate]/[raf]/index.js:75:1
  
  - bootstrap:19 
    website-corporate/webpack/bootstrap:19:1
  
  - static-entry.js:212 
    website-corporate/.cache/static-entry.js:212:27
  
  - emotion-styled-base.esm.js:124 
    [website-corporate]/[@emotion]/styled/base/dist/emotion-styled-base.esm.js:124:1
```

**Comment by Mastermindzh** [comment]
Seems to be a problem because 'window' isn't available at build time.
There are some good tips in here: https://github.com/gatsbyjs/gatsby/issues/8612

**Comment by pierangelo1982** [comment]
same problems on nextjs!

**Comment by mastepanoski** [comment]
On NextJS (Server Rendering):

> Server Error
ReferenceError: self is not defined
This error happened while generating the page. Any console logs will be displayed in the terminal window.

It works fine in 6.4.1version.

To use UMD with SSR: [UMD build can't be used in node env #6784 ](https://github.com/webpack/webpack/issues/6784)

> That window there seems to be the issue. The documentation suggests that instead of window, I should have typeof self !== 'undefined' ? self : this. If I change that manually my library works in both the browser and Node environments. Obviously changing it myself is not the solution. @MarkRabey

**Comment by linkb15** [comment]
For Next.js Usage.. use dynamic import https://nextjs.org/docs/advanced-features/dynamic-import#basic-usage

```tsx
import dynamic from 'next/dynamic'
const CookieConsent = dynamic(() => import('react-cookie-consent'), { ssr: false })
```
the self is not defined on the SSR.. so by doing this we just use the cookie consent in the client side..

**Comment by worknovel** [comment]
I changed the "self" to "this" and it works on Next.JS 
https://github.com/worknovel/react-cookie-consent/tree/patch-1

**Comment by Mastermindzh** [comment]
@linkb15 ,

We should add your instructions to the README under a header to fix SSR/build issues.
I can do this next week (for Gatsby as well), but you are always welcome to create a PR.

Something like this:
```md
## Frameworks
.. some need work... 

### ssr issues

because self isn't.... at ssr time .... we need to .... to make sure it loads in the client browser only

### nextjs

// your code block
```

@worknovel for gatsby a much nicer way to solve this is to provide a null-loader according to the docs: https://www.gatsbyjs.com/docs/debugging-html-builds/#fixing-third-party-modules

```js
exports.onCreateWebpackConfig = ({actions, stage}) => {
    if (stage === "build-html") {
        actions.setWebpackConfig({
            module: {
                rules: [
                    {
                        test: /react-cookie-consent/,
                        use: ['null-loader']
                    },
                ],
            }
        })
    }
};
```

**Comment by linkb15** [comment]
@Mastermindzh created a PR for the documentation

**Comment by AlexandreVerhoye** [comment]
Hi ! 

How can i use this import with next/dynamic ? 

`import { Cookies, getCookieConsentValue } from "react-cookie-consent";`

I already did this import : `const CookieConsent = dynamic(() => import('react-cookie-consent'), { ssr: false })`

Thx

**Comment by linkb15** [comment]
@AlexandreVerhoye for this case we can use dynamic import es2020 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#dynamic_imports

since `next/dynamic` is mentioned only for Components

```tsx
useEffect(() => {
  (async () => {
    const { getCookieConsentValue, Cookies } = await import('react-cookie-consent')

    getCookieConsentValue('test')
    Cookies.get()
  })()
}, [])
```

**Comment by Mastermindzh** [comment]
Can either of you confirm this line to work?
https://github.com/iannbing/react-simple-tree-menu/pull/53/files#diff-3e31f6f375484b2dfd4629faed9e5183ac6568ebdbc67ec752e10c41a35250c6R14

I might have time to try it tomorrow but no earlier.

**Comment by Mastermindzh** [comment]
The fix above works. Version [7.0.1](https://www.npmjs.com/package/react-cookie-consent/v/7.0.1) doesn't throw `self is not defined` in Gatsby or NextJS projects without async imports :)

Enjoy!
