### ISSUE TITLE
Use custom button instead of the default one

### ISSUE THREAD

**Issue by tiavina-mika** [Mastermindzh/react-cookie-consent#139]
I vant something like this:

![image](https://user-images.githubusercontent.com/42656064/146668334-23e242cc-8ae4-4e05-a4c1-a7f694ae50dd.png)

is it possible to use a button as a children of the CookieConsent instead of the default one?

**Comment by Mastermindzh** [comment]
Hey @tiavina-mika 

> is it possible to use a button as a children of the CookieConsent instead of the default one?

Yes, you can add buttons to the children. Simply disable the styles of the built-in button and make your own:

```jsx
  <CookieConsent buttonStyle={{ display: 'none' }}>
    <p>Some text</p>
    <span style={{ display: 'flex', justifyContent: 'space-between' }}>
      <button>First child button</button>
      <button>second child button</button>
    </span>
  </CookieConsent>
```

Though you can also style the built-in buttons in any way that you want :)

**Comment by tiavina-mika** [comment]
Thanks,
but if I set the buttonStyle to ```buttonStyle={{ display: 'none'}}```
I can not access the onAccept props:
```      onAccept={() => console.log('accept me')}
```

**Comment by arthwood** [comment]
@tiavina-mika I realised (by looking into source code) that your custom button must accept `onClick` prop (mine had `onPress`). @Mastermindzh maybe worth mentioning this in documentation?

**Comment by Mastermindzh** [comment]
@arthwood , are you on react native? onPress is a react-native use-case 😄.
But sure, we can mention it in the docs.

**Comment by arthwood** [comment]
@Mastermindzh Nope, I'm obviously on web and I have my custom button component. Good guess though as we have a RN app too, so I've made the names for props a common interface :slightly_smiling_face:

**Comment by devansh1305** [comment]
Hello, I am currently using this package and I am not sure how to access the onAccept() function from my custom button. Could you provide a small example or implementation for this?

**Comment by bbernag** [comment]
For everyone that wants to use a custom button here is a workaround

- Hide buttons with `buttonStyle={{ display: "none" }}`
- Create a ref ` const cookieConsentRef = React.useRef(); in your component`
- Set ref in `<CookieConsent ref={cookieConsentRef} buttonStyle={{ display: "none" }} />`
- On your custom button inside the onClick callback  run `cookieConsentRef.current.accept();`

This works for `decline` as well
