### ISSUE TITLE
getCookieConsentValue() returns strings that look like boolean values

### ISSUE THREAD

**Issue by iosonosempreio** [Mastermindzh/react-cookie-consent#146]
I suggest making them actual boolean values, or changing the string into something different from true / false since it is confusing (and messes with React).

**Comment by Mastermindzh** [comment]
Hey @iosonosempreio ,

Cookies can only store strings :)
You are however free to change the content of the cookie:

```ts
<CookieConsent 
	cookieValue="whatever you want"
>
</CookieConsent>
```

Hope that helps!
