### ISSUE TITLE
getCookieConsentValue returning undefined

### ISSUE THREAD

**Issue by javismiles** [Mastermindzh/react-cookie-consent#156]
Hi,
I import getCookieConsentValue
import CookieConsent, { Cookies, getCookieConsentValue }from "react-cookie-consent";

but when I call it with getCookieConsentValue(), I get undefined returned

whats the right way to include it in a react app?
I need to know whats the current status of the cookie

thanks very much

**Comment by jcolvard** [comment]
Seeing the same thing. I can see in the Chrome inspector -> Application -> Cookies that the cookie gets added on Accept, and that the value is true. but `getCookieConsentValue()` brings back undefined

**Comment by NEDDL** [comment]
Hi @javismiles, could you please explain how you solved the issue? Because I couldn't find the problem. Mine still prints undefined.

**Comment by Mastermindzh** [comment]
`getCookieConsentValue` takes 1 parameter: `name`.
If you use a custom cookie name (`cookieName` attribute) then you will have to pass that same value to `getCookieConsentValue`.

By default the cookieName is `CookieConsent`, so if you call `getCookieConsentValue()` it will use `CookieConsent` as the default parameter. If we customize the name, we have to customize the call...

```jsx
<CookieConsent
  cookieName="myAwesomeCookieName2"
>
</CookieConsent>
```
Then use the method with that same name:

```jsx
getCookieConsentValue("myAwesomeCookieName2")
```

Enjoy!
