### ISSUE TITLE
react-cookie-consent / MUI integration

### ISSUE THREAD

**Issue by jcolvard** [Mastermindzh/react-cookie-consent#157]
Hello,

Do you have any examples of integrating an MUI Button component with the react-cookie-consent tool?

I can:

```
import Button from '@mui/material/Button'
import CookieConsent from 'react-cookie-consent'
```

then

```
<CookieConsent
        location='bottom'
        buttonText='I Accept'
        cookieName='myCookieBanner'
        expires={365}
        ButtonComponent={Button}
        disableButtonStyles
      >
        <span style={{ fontSize: '14px' }}>
          This website uses cookies to enhance the user experience.
        </span>
</CookieConsent>

```

I can get my default MUI button to render properly. But how do I declare an MUI `variant='contained'` property on that `Button`? 

Do I need to go through the react-cookie-consent api `customButtonProps` to then leverage the MUI api for `variant`?

Can someone direct me to any examples?

Thanks very much for any assistance!

**Comment by Mastermindzh** [comment]
There is property for `extraButtonProps` which will be spreak on the button. So this should work:

```
<CookieConsent
       ....
        customButtonProps={{variant:"contained"}}
      >
     ....
</CookieConsent>

```
