### ISSUE TITLE
customButtonProps on decline button?

### ISSUE THREAD

**Issue by modestjoust** [Mastermindzh/react-cookie-consent#159]
Hello, 

Looks like there's only a `customButtonProps` that is used for the accept button. Could we add/split into two different props? A `customAcceptButtonProps` and a `customDeclineButtonProps`?

Thanks all!

**Comment by Mastermindzh** [comment]
Yep, we can.

Will be released later today 😄

**Comment by Mastermindzh** [comment]
It has been included in version [7.5.0](https://www.npmjs.com/package/react-cookie-consent/v/7.5.0).
It's called `customDeclineButtonprops` and works exactly the same way as the existing `customButtonProps`.

Enjoy!
