### ISSUE TITLE
Disable location styling.

### ISSUE THREAD

**Issue by dimitrisfasoulas** [Mastermindzh/react-cookie-consent#16]
I would like to style the component through CSS classes that I use in my app, but the location prop is enforcing some style. 

I can disable this by passing a bogus string on location but then I will get an error in console:

_Warning: Failed prop type: Invalid prop `location` of value `none` supplied to `CookieConsent`, expected one of ["top","bottom"]._

It would be nice if we could provide null to location to remove said styling or if disableStyles would also disable said styles, or if we had another prop, for example disablePositioningStyles.

If you find one of the above solutions acceptable I could work on a pull request for it.

**Comment by Mastermindzh** [comment]
It's in [1.4](https://www.npmjs.com/package/react-cookie-consent/v/1.4.0) :D
