### ISSUE TITLE
Cookie content in Safari and Brave expires in a week

### ISSUE THREAD

**Issue by zemlanin** [Mastermindzh/react-cookie-consent#160]
- https://www.cookiestatus.com/safari/#first-party-cookies
- https://www.cookiestatus.com/brave/#first-party-cookies

`localStorage` has less-strict restrictions (none in Brave; "7 days after using a site" instead of "7 days after setting a cookie" in Safari)

**Comment by Mastermindzh** [comment]
react-cookie-consent does not aim to bypass any limitations set by browsers, in fact, it uses the browser to set a cookie.
With the `onAccept` event or custom buttons you could work around this if you really wanted to.

Best of luck!
