### ISSUE TITLE
React Native - View config getter for component 'div' must be a function (received 'undefined')

### ISSUE THREAD

**Issue by Haykys** [Mastermindzh/react-cookie-consent#162]
On React Native I'm getting the error written in title of this issue. Any idea why ? Is there some compatibility issue with RN ? 

The component:

```
import React from 'react';
import CookieConsentPkg from 'react-cookie-consent';
import { Text, View } from 'react-native';

const CookieConsent = (): JSX.Element => (
  <View>
    <CookieConsentPkg>
      <Text>This website uses cookies to enhance the user experience.</Text>
    </CookieConsentPkg>
  </View>
);

export default CookieConsent;
```

**Comment by Mastermindzh** [comment]
This is a web component, using it in React Native is not currently supported.
The error you get is , basically, telling you that you can't use `div`. Which this library does

You can use a WebView if you really want to use this 😄
