### ISSUE TITLE
No types for accept and decline methods

### ISSUE THREAD

**Issue by matchmakers69** [Mastermindzh/react-cookie-consent#165]
There are no types (Typescript) for methods accept(); and declined(); required to create functionality to accept or decline cookies when `custom` buttons were added.

Had to add `  const handleAcceptButtonClick = () => {
    // @ts-ignore
    cookieConsentRef?.current?.accept?.();
  };`

**Comment by Mastermindzh** [comment]
Hey @matchmakers69,

`accept` and  `decline` are meant to be internal functions so they don't have types (as the source is in JavaScript).
Going from the name of your handler you simply want to do something on accept, you can do that with the `onAccept` property:

```tsx

const handleAcceptButtonClick = (acceptedByScrolling) => { 
   // your logic
   if (acceptedByScrolling) {
      // triggered if user scrolls past threshold
      alert("Accept was triggered by user scrolling");
    } else {
      alert("Accept was triggered by clicking the Accept button");
    }
};

<CookieConsent onAccept={handleAcceptButtonClick}></CookieConsent>
```

Accept is automatically called and it will call your function 😄 
Hope that helps!

**Comment by matchmakers69** [comment]
Thanks for reply but this is not exactly what i meant, basically i need to hide all default buttons and show my custom buttons, Accept button where i need to run accept method and Manage cookies button, please view my code in full plus design

`import { useEffect, useRef } from "react";
import { palette } from "theme/palette";
import * as S from "./CookiesConsentBar.styled";
import CookieIcon from "assets/icons/cookie.svg";
// eslint-disable-next-line import/no-unresolved
import AnalyticsConfiguration from "memberWebAppCustom/AnalyticsConfiguration";
import CookieConsent, { Cookies, getCookieConsentValue } from "react-cookie-consent";
import { initGA } from "utils/cookies/initGA";
import DoneIcon from "@mui/icons-material/Done";
import { Box, Typography } from "@mui/material";
import Container from "components/ui/Container";
import Button from "../Button";

const CookiesConsentBar = () => {
  const cookieConsentRef = useRef<CookieConsent | null>(null);

  const handleOpenCookiesModal = () => {
    console.log("open modal");
  };
  const handleAcceptCookie = () => {
    if (AnalyticsConfiguration.REACTGA_TRACKER_ID) {
      initGA(AnalyticsConfiguration.REACTGA_TRACKER_ID);
    }
  };

  const handleAcceptButtonClick = () => {
    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
    // @ts-ignore
    cookieConsentRef?.current?.accept?.();
  };

  const handleDeclineCookie = () => {
    //remove google analytics cookies
    Cookies.remove("_ga");
    Cookies.remove("_gat");
    Cookies.remove("_gid");
  };

  useEffect(() => {
    const isConsent = getCookieConsentValue();
    if (isConsent === "true") {
      handleAcceptCookie();
    }
  }, []);

  return (
    <>
      <CookieConsent
        location="bottom"
        onDecline={handleDeclineCookie}
        onAccept={handleAcceptCookie}
        ref={cookieConsentRef}
        expires={365}
        buttonText="Accept"
        buttonStyle={{ display: "none" }}
        style={{
          background: palette.background.default,
          boxShadow: "0px -2px 7px rgba(0, 0, 0, 0.25)",
          color: palette.text.default,
          padding: "15px 30px",
        }}
      >
        <Container>
          <Box
            sx={{
              mb: 8,
            }}
          >
            <S.CookiesConsentHeader>
              <S.CookieIconwrapper>
                <S.Img src={CookieIcon} alt="cookie-icon" />
              </S.CookieIconwrapper>
              <Typography sx={{ mb: 0 }} variant="h3" component="h3">
                Cookies
              </Typography>
            </S.CookiesConsentHeader>

            <Typography component="p" variant="body1">
              We use analytics tracking cookies to help us improve the functionality of our website
              by collecting information and reporting on your use of the website. We do not collect
              any personally identifiable information. You can manage your cookie settings and
              switch off non-essential cookies via the “Manage cookies” button below.
            </Typography>
          </Box>
          <Box
            sx={{
              display: "flex",
              alignItems: "center",
              flexWrap: "nowrap",
            }}
          >
            <Box
              sx={{
                width: "200px",
                mr: 6,
              }}
            >
              <Button fullWidth onClick={handleOpenCookiesModal} variant="outlined">
                Manage cookies
              </Button>
            </Box>

            <Box
              sx={{
                width: "200px",
              }}
            >
              <Button
                endIcon={<DoneIcon />}
                color="secondary"
                fullWidth
                onClick={handleAcceptButtonClick}
                type="button"
                data-testid="edit-button"
              >
                Accept
              </Button>
            </Box>
          </Box>
        </Container>
      </CookieConsent>
      {/* TO DO - add cookies modal here */}
    </>
  );
};

export default CookiesConsentBar;
`
![image](https://user-images.githubusercontent.com/16280618/180749571-dc87b398-fbd9-40de-9e68-cc47a62bed5e.png)

**Comment by Mastermindzh** [comment]
Your bar looks pretty good 😄!

Unfortunately this can't really get a fix until I redo the package in Typescript.
I'll put it on the backlog and I will track progress here: https://github.com/Mastermindzh/react-cookie-consent/issues/90

Shouldn't be too difficult to set up next weekend 😉 !

**Comment by Mastermindzh** [comment]
![image](https://user-images.githubusercontent.com/4190290/182019715-83e46087-716c-48af-bc91-abd1882ce66d.png)

Better 😄 ?

**Comment by Mastermindzh** [comment]
Version [8.0.1](https://www.npmjs.com/package/react-cookie-consent/v/8.0.1) has been released and that feature full typescript support 😄 

The [demo page](https://mastermindzh.github.io/react-cookie-consent/) has been replaced with a storybook version as well.

Enjoy!
