### ISSUE TITLE
GDPR Cookie Banner Europe law

### ISSUE THREAD

**Issue by Leonardll** [Mastermindzh/react-cookie-consent#168]
Hi Guys, It is more a question than a issue. Going through your documentation I am unable to see how to implement a cookie banner in the gdpr European law style where user can customised his preferences 
Can you advise on this please ?

**Comment by Mastermindzh** [comment]
Hey @Leonardll,

This package offers no configuration options. It only allows accepting/declining all cookies out of the box.

Of course, the component is extensible so you can build around it.

See this issue for some helpful tips:
https://github.com/Mastermindzh/react-cookie-consent/issues/124

Good luck!

**Comment by Leonardll** [comment]
thanks, for this @Mastermindzh :). 
Don't you think that this is feature request worth to be added to your library?

**Comment by Leonardll** [comment]
also, can you advise, how to add an extra button using your ButtonComponent ,please . I am struggling with it.
```
  <CookieConsent
          debug={true}
          onAccept={handleAcceptCookie}
          onDecline={handleRejectCookie}
          cookieName="CookieConsent"
          cookieValue={getCookieConsentValue()}
          sameSite="strict"
          buttonWrapperClasses="d-flex"
          enableDeclineButton
          declineButtonStyle={{
            background: "#245564",
            padding: "10px 20px",
            borderRadius: "16px",
            fontSize: "1em",
            color: "#ffff",
            display: "flex",
            alignContent: "center",
            justifyContent: "center",
          }}
          ariaAcceptLabel="Accept all cookies"
          ariaDeclineLabel="Decline all cookies"
          flipButtons
          location="bottom"
          style={{
            background: "#ffff",
            textAlign: "center",
            color: "#245564",
            fontSize: "1em",
            display: "flex",
            alignContent: "center",
            justifyContent: "center",
          }}
          buttonStyle={{
            color: "#ffff",
            background: "#245564",
            padding: "10px 20px",
            borderRadius: "16px",
            fontSize: "1em",
            display: "flex",
            alignContent: "center",
          }}
          expires={1}
          ButtonComponent="button"
          customButtonProps={{
            color: "#ffff",
            background: "#245564",
            padding: "10px 20px",
            borderRadius: "16px",
            fontSize: "1em",
            display: "flex",
            alignContent: "center",
          }}
        >
          This site uses cookies. Please See our privacy
          <Link href="/policy" passHref>
            <a style={{ color: "#5ab4ab", textDecoration: "none" }}> policy </a>
          </Link>
          for more information
        </CookieConsent>
```

**Comment by Mastermindzh** [comment]
Hey @Leonardll,

I don't really have the time to invest in expanding the library by that much.
I would also just create a new one that can hook into this one btw.

## the ButtonComponent

As for your question, the `ButtonComponent` is meant to replace the existing two buttons.
If you have [mui' Button](https://mui.com/material-ui/react-button/) for example you would have something like this:
```tsx
  <CookieConsent
    ButtonComponent={Button}
    customButtonProps={{ variant: "contained", style: { marginRight: "10px" } }}
  >
    This website uses cookies to enhance the user experience.
    <span style={{ fontSize: "10px" }}>This bit of text is smaller :O</span>
  </CookieConsent>
```
Which would render:
![image](https://user-images.githubusercontent.com/4190290/182016622-b5dbeb1d-7f12-4a0c-83a8-89c8568dc510.png)

## adding another button

Adding another button can be done by adding it as a child:

```tsx
  <CookieConsent {...args}>
    <button style={{ color: "gray" }}>I am a custom config button</button>{" "}
    <span style={{ fontSize: "10px" }}>This bit of text is smaller :O</span>
  </CookieConsent>
```
Which would get you:
![image](https://user-images.githubusercontent.com/4190290/182017061-d253b823-786d-48c7-97e1-77a97f112556.png)

From there you are free to style the button as you wish (I just changed the color as an example)

**Comment by Mastermindzh** [comment]
I've added the mui button as an example in [storybook](https://mastermindzh.github.io/react-cookie-consent/?path=/story/cookieconsent--custom-mui-button)

Feel free to re-open if there are any issues.
