### ISSUE TITLE
Accept cookies method to available across the app

### ISSUE THREAD

**Issue by matchmakers69** [Mastermindzh/react-cookie-consent#169]
Would be possible to use acceptCookies function in different parts of the app? Basically what I need is to accept cookies on cookies page without using:
```const [isCookieAccepted, setIsCookieAccepted] = useState(false);
 
const handleAcceptRejectCookies = () => {
 if (isCookieAccepted) {
 document.cookie = "CookieConsent=true";
 } else {
document.cookie = "CookieConsent=false";
 }
  snackSuccess(t("updatedCookiesSuccess"));```

**Comment by Mastermindzh** [comment]
Hey @matchmakers69,

The accept functionality is not available outside of the bar.
You can of course set the cookie manually but that defeats the entire purpose of the package.

Wish you the best with your app though!
