### ISSUE TITLE
Is there "agree" method without click agree using method

### ISSUE THREAD

**Issue by lgj9172** [Mastermindzh/react-cookie-consent#172]
I should automatic agree when sign in.
When someone sign in, I should remove the cookie consent and mark it as agreed.
Is there any method?

**Comment by lgj9172** [comment]
I should automatic agree when sign in.
When someone sign in, I should remove the cookie consent and mark it as agreed.
Is there any method?

**Comment by Mastermindzh** [comment]
You have a few options, you can get a reference to the component and call the public `accept` method or you can manually set the cookie using the defaultCookieConsentName.
