### ISSUE TITLE
'CookieConsent' cannot be used as a JSX component

### ISSUE THREAD

**Issue by van4oza** [Mastermindzh/react-cookie-consent#173]
TS2786: 'CookieConsent' cannot be used as a JSX component.
  Its instance type 'CookieConsent' is not a valid JSX element.
    Type 'CookieConsent' is missing the following properties from type 'ElementClass': context, setState, forceUpdate, props, refs

**Comment by Mastermindzh** [comment]
Hey,

Please share a reproducible example repo because I can't reproduce the issue from just this error.
Seems to be a misconfiguration in your codebase though 😄

**Comment by edgarSaavedraTergar** [comment]
hello I would like your help to know how to apply a react function in the buttonText. @Mastermindzh 
My sample is: <span className="fa fa-check"></span> Accept
how am i implementing it: buttonText= CustomButtonText || buttonText= () => CustomButtonText

I'm having errors with my examples

**Comment by Mastermindzh** [comment]
@edgarSaavedraTergar,

Please start a new issue and include a properly blocked (code block) code example.

**Comment by felixhaeberle** [comment]
Had this issue too: Check if you have installed `yarn add @types/react --dev` or `npm install @types/react --save-dev`

**Comment by dfberry** [comment]
I ran into the initial JSX error mentioned. The solution that eventually worked for me was to blow away node_modules and install everything (npm install) again. I tried restarting my TSServer in VSCode but that didn't help.
