### ISSUE TITLE
decline Button Component

### ISSUE THREAD

**Issue by rtgfxp** [Mastermindzh/react-cookie-consent#174]
Thank you for your wonderful code,
I did not understand how to make the decline button also MUI type,
is it possible to add  DeclineButtonComponent?
Thank you very much

**Comment by Mastermindzh** [comment]
Hey,

No problem!

Defining the "ButtonComponent" will apply it to both buttons.
You can see an example story here:

https://github.com/Mastermindzh/react-cookie-consent/blob/master/stories/stories/muiButtons.story.ts

Which renders both a primary accept, and a secondary decline in MUI style:
![image](https://user-images.githubusercontent.com/4190290/200588765-4656f9eb-c59d-4238-bf6d-8dc31481b5b7.png)
