### ISSUE TITLE
Disable auto hiding of the component

### ISSUE THREAD

**Issue by dimitrisfasoulas** [Mastermindzh/react-cookie-consent#18]
For the purpose of animating the component when the user clicks accepts, it would be nice if we had an option to instead of removing the component by setting the state visible to false and thus returning null on render, to let ’onAccept’ handle the hiding.

I propose adding a prop `autoHide: PropTypes.bool` that defaults to `true` and changing `accept()` to 
```javascript
  accept() {
    const { cookieName, expires, autoHide } = this.props;

    Cookies.set(cookieName, true, { expires: expires });
    if (autoHide) {
      this.setState({ visible: false });
    }
  }
```

If you agree I can create a pull request with the above changes.

_Also thank you so much for creating this and replying so fast 🥇_

**Comment by Mastermindzh** [comment]
Good one, let's do this as well!

**Comment by Mastermindzh** [comment]
Added in [1.5](https://www.npmjs.com/package/react-cookie-consent/v/1.5.0)
