### ISSUE TITLE
HttpOnly option on Cookie settings

### ISSUE THREAD

**Issue by matheusmellocss** [Mastermindzh/react-cookie-consent#181]
First of all, thank you all for this open-source project. It helped us a lot in our project.

I have a question regarding to the use of HttpOnly option at the CookieConsent React component.

```
<CookieConsent
        ...
        cookieSecurity={true}
        extraCookieOptions={{
          HttpOnly: true,
        }}
      >
```

I tried both "HttpOnly" and "httpOnly", but when I set this to true the Cookie does not work. Is there any suggestion on how should we use the HTTP Only property when setting a cookie?

**Comment by Mastermindzh** [comment]
Hey,

You can't access httpOnly cookie through client-side JS code.
Setting the cookie as httpOnly will ensure that client-side JS code can't read it and the bar will keep showing up.

See: https://owasp.org/www-community/HttpOnly
