### ISSUE TITLE
How to Close the CookieConsent window with onAccept

### ISSUE THREAD

**Issue by IceCodeProductions** [Mastermindzh/react-cookie-consent#182]
I have the <CookieConsent hideOnAccept visible="show" and logic created in the onAccept= {() =>{ stuff.. need Command to Close window  } which all works.  My problem is that I have not been able to find a way to close the CookieConsent window within the onAccept procedure.  I have looked into the provided documents and search stackoverflow.

**Comment by Mastermindzh** [comment]
`visible` overrides everything 😄.
Simply set visible to false yourself and the bar will disappear!
