### ISSUE TITLE
Consent Modal disappears when I scroll down

### ISSUE THREAD

**Issue by andrei-bh** [Mastermindzh/react-cookie-consent#183]
Hi
It disappears when I scroll down the page.
And the problem is that if I remove scroll event listener in the parent component, it works fine.
What's wrong with it?

**Comment by Mastermindzh** [comment]
Hey,

You can control scroll behavior through the properties, see [this README chapter](https://github.com/Mastermindzh/react-cookie-consent#accept-on-scroll) for an example.

If you have more issues, please open the issue back up and provide some code to replicate the issue 😄.

Thanks!

**Comment by andrei-bh** [comment]
@Mastermindzh It didn't work even though I added `acceptedOnScroll={false}`

**Comment by andrei-bh** [comment]
@Mastermindzh I don't have permission to reopen it since you closed it. 
Anyway, could you check my above code?
