### ISSUE TITLE
style margin bottom and bottom don't work

### ISSUE THREAD

**Issue by dzienisz** [Mastermindzh/react-cookie-consent#185]
when I try to add some **margin** to the cookie consent box I changed it to **position: sticky** and added **margin bottom** but it don't work also adding **bottom** don't work either it's beeing changed to **bottom 0** whatever value I put inside

**Comment by iamsuyashpatel07** [comment]
https://github.com/Mastermindzh/react-cookie-consent/issues/20#issuecomment-1510995611 read this

**Comment by dzienisz** [comment]
Thanks, so it's not easy to do. Maybe it should be in documentation?
