### ISSUE TITLE
Update documentation to show support for custom cookie name

### ISSUE THREAD

**Issue by GodOfGrandeur** [Mastermindzh/react-cookie-consent#186]
Both the `getCookieConsentValue()` and `resetCookieConsentValue()` methods in the documentation don't show that if defining a custom cookie name using the `cookieName` prop then this will need passing in as parameter. 

Would be nice to update the documentation to show this. 

getCookieConsentValue(name) - optional name of cookie must be passed in if changed in the cookieName prop.
resetCookieConsentValue(name) - optional name of cookie must be passed in if changed in the cookieName prop.

**Comment by Mastermindzh** [comment]
Hey @GodOfGrandeur,

Do you mean in the README file?

**Comment by GodOfGrandeur** [comment]
Yes
