### ISSUE TITLE
I got error when I install package in nextjs 13

### ISSUE THREAD

**Issue by Tony-Stark-Jr** [Mastermindzh/react-cookie-consent#197]
This is flowing error I got in terminal
 ⨯ node_modules/react-cookie-consent/dist/react-cookie-consent.esm.js (34:48) @ prototype
 ⨯ TypeError: Cannot read properties of undefined (reading 'prototype')
    at _inheritsLoose (webpack-internal:///(rsc)/./node_modules/react-cookie-consent/dist/react-cookie-consent.esm.js:49:51)

**Comment by Mastermindzh** [comment]
Hey,

react-cookie-consent is only available client-side. So you have to tell Next that your component is client-side only, you can do that like this:

```tsx
'use client'
 
import { useState } from https://github.com/facebook/react/tree/master/packages/react
 
export default function Counter() {
  const [count, setCount] = useState(0)
 
  return (
    <div>
      <p>You clicked {count} times</p>
      <button onClick={() => setCount(count + 1)}>Click me</button>
    </div>
  )
}
```

see: https://github.com/Mastermindzh/react-cookie-consent/issues/194

**Comment by Mastermindzh** [comment]
Sorry, wrong button 😄
