### ISSUE TITLE
Hide on scroll

### ISSUE THREAD

**Issue by michaelzoidl** [Mastermindzh/react-cookie-consent#21]
Hey @Mastermindzh,

at first, nice module, good API and it just works.
I've a question, what do you think about a `acceptOnScroll` option? I'v seen this functionality in other modules and i'am wondering if its also a case for this one? 

So some kind of `window.addEventListener('scroll')` which executes `this.accept` on scroll start.

But at first it would be interesting if this is even allowed.

**Comment by Mastermindzh** [comment]
Hey @michaelzoidl ,

First up, thanks for the kind words! much appreciated.

I'm not sure whether this would be allowed to be honest.
One could argue that no consent is given if the user scrolls to find out more.

I'm hesitant to include it unless someone can point out to me that this functionality would be considered legal.

Tell you what, let me have a couple of days to maul this over and I'll see what I can do for ya. I don't want to encourage unlawful behavior but adding an extra optional option is definitely possible.

**Comment by Byloor** [comment]
I also want to add one more question, similar to the issue. I am not sure it is acceptable/legal either! 
Can we have a 'I do not accept' option along with accept button? I have seen this option in some websites.

**Comment by michaelzoidl** [comment]
@Mastermindzh nice :) i will also check if thats legal, maybe we find a lawer for this case, you're right, this shouldn't available in the module if its not allowed.

@Byloor and what happens when somebody clicks "i do not accept"? Would you expect some kind of callback so the module notifies you that the users didn't allow the cookies thing. Btw, IMO sounds like an extra issue...

**Comment by Byloor** [comment]
@michaelzoidl 
Yes, cookies wont be saved (or may be few, if  it is really essential for the service provided by the website that the user needs). 
Check out : 

- https://cookieconsent.insites.com/documentation/disabling-cookies/

- https://eugdprcompliant.com/cookies-consent-gdpr/

**Comment by Mastermindzh** [comment]
@Byloor, you can simply add another button by declaring it in code like so:

```
<CookieConsent>
    Cookie text here
    <button onClick={() => alert("don't allow cookies")}>Don't accept</button>
</CookieConsent>
```

react-cookie-consent is meant to be a simple cookiebar which asks for permission, more advanced solutions should take care of handling cookies.

e.g you could make a react-cookie-manager which would be used to set cookies (e.g `cookieManager.addCookie({}, "essential"` and offer some way of managing those so that the user can enable / disable them at will.)

**Comment by Mastermindzh** [comment]
@michaelzoidl ,

Let me know about the legal status :)

Feature isn't hard to implement so I can start working on it tonight/tomorrow and we'll merge if it's legal, if not we'll keep it in a branch :smile:

**Comment by michaelzoidl** [comment]
@Mastermindzh nice :) sounds great!
So I've not talked to an lawer yet but i've seen multiple components / modules which are support this feature, so maybe asking them if they've experience with this would also help.

I've also seen a definition when this should happen and an argument why it should be seen as conform:
> Scrolling down should be considered as a consent. Scrolling will be treated as a consent if a person has scrolled for ~25%. So an accidental scroll will NOT be taken for a consent (which is good!).

**Comment by Mastermindzh** [comment]
Welp, didn't have time today....

I will put it in over the weekend, your sources are great and I agree with the 25% scroll thing though I'd like to make that a parameter instead.

**Comment by Mastermindzh** [comment]
Added in [v1.6](https://www.npmjs.com/package/react-cookie-consent/v/1.6.0) :)

Enjoy!

**Comment by michaelzoidl** [comment]
@Mastermindzh you're awesome.. thank you! :)

**Comment by pdipietro** [comment]
@Mastermindzh I found your component very useful. Thank you.
But I'd like to add a different use case, if it possible.
I have the bar into my home page, which is just a non scrolling page.
I used bot the `accept` and `decline` button, but I would  like to have an implicit accept if the user clicks anywhere on the page, without scrolling.
How can I accomplish that?
