### ISSUE TITLE
Object.values is not a function

### ISSUE THREAD

**Issue by Epimetheus89** [Mastermindzh/react-cookie-consent#22]
Hi,

In IE the Object.values function that is used in PropTypes is not available. It could either be resolved by adding a polyfill or by replacing with `Object.keys(OPTIONS).map(key => OPTIONS[key])`.

**Comment by Mastermindzh** [comment]
Will fix this tonight. Thanks.

Any other problems in IE? I don't have Windows :)

**Comment by Mastermindzh** [comment]
Implemented this in [1.6.1](https://www.npmjs.com/package/react-cookie-consent/v/1.6.1)
