### ISSUE TITLE
Add cookie options

### ISSUE THREAD

**Issue by dev-cloudbd** [Mastermindzh/react-cookie-consent#23]
Request for the ability to add cookie options to the consent cookie created when accepted.

We use multiple subdomains on our site such as www, docs, and manage and would like to have all 3 subdomains use the same cookie consent bar cookie (accept once works on all subdomains). For this we need to be able to set the domain of the cookie to the top level domain of our site as the default will limit it to the subdomain only. I'm sure others may find adding generic cookie options to the cookie useful as well.

**Comment by Mastermindzh** [comment]
We can add this as a parameter for sure.
I could add a parameter "extraCookieOptions" which takes a simple object:

```
{
domain: "example.com",
foo: "bar"
}
```

and spread it on the existing cookie options (e.g expires).

This would allow for maximum flexibility.
I'll see whether I can add this tonight.

**QUICKFIX**
You can impoort Cookie from react-cookie-consent like so:

`import {Cookie} from "react-cookie-consent"`

and use it to set an extra cookie untill this is implemented

**Comment by Mastermindzh** [comment]
Implemented in [1.7.0](https://www.npmjs.com/package/react-cookie-consent/v/1.7.0).

Enjoy!

**Usage example:**
```
<CookieConsent 
    extraCookieOptions={{domain: 'myexample.com'}}
>
    cookie bar
</CookieConsent>
```

**Comment by akhilumapathe** [comment]
Hi, 
Good work with this module. Appreciate. (claps) 

Can you please advice me on below? 

I have one domain. Users access with and without www. I need the show and accept once only which should in turn accept them all at once. How can I achieve this?

**Comment by Mastermindzh** [comment]
Thanks for the kind words :)

There is actually nothing (good) you can do about it in **code** as the storing of a cookie happens by the browser and most choose to separate www and non-www domains.

Different browsers might result in different results so you'd be chasing browser implementation at that point.

The best advice would therefore be to redirect to one or the other (on your webserver). I prefer redirecting everything to www.

**The not so good solution**:

There is something you.... could do... but really, that should only be done if you don't have access to the web server itself.

If you set a cookie with the domain ".domain.com" it will set the cookie for **all** subdomains, which happens to include www. as well.
