### ISSUE TITLE
Looks awesome but needs typescript types.  

### ISSUE THREAD

**Issue by burtonator** [Mastermindzh/react-cookie-consent#27]
Looks awesome but needs typescript types.  ... I might write some if I can't find anything better.

Thanks!

**Comment by Mastermindzh** [comment]
I don't really use typescript for React.
If you create a PR with the typings file I will merge it for sure :)

**Comment by Saturate** [comment]
I could use these types as well, if I find the time I'll add them.

**Comment by Mastermindzh** [comment]
I'm glad to report that @Saturate's PR was merged in [v1.10](https://www.npmjs.com/package/react-cookie-consent/v/1.10.0)

Thanks again man!
