### ISSUE TITLE
FYI - published bucklescript bindings for react-cookie-consent

### ISSUE THREAD

**Issue by ctbucha** [Mastermindzh/react-cookie-consent#28]
@Mastermindzh this component works great, but my project is in ReasonReact, so I published some BuckleScript bindings for it. (https://github.com/ctbucha/bs-react-cookie-consent)

**Comment by Mastermindzh** [comment]
Cool! Hadn't heard of BuckleScript before so I'm going to check out ReasonReact for sure!

I have added your project to the list of projects that include react-cookie-consent :+1: 

Thanks for the contribution!
