### ISSUE TITLE
Question about dependencies

### ISSUE THREAD

**Issue by amytych** [Mastermindzh/react-cookie-consent#30]
Hi there, I'm interested in using your consent component and I'm curious about some of the dependencies, would love it if you could clarify for me:

1. what are the reasons for including `webpack-copy-plugin` in the dependencies? is it somehow used by the final built version?

2. what are the reasons to have `react` as dependency instead of peer dependency?

**Comment by Mastermindzh** [comment]
Hey amytych,

1. Oh noes! this happened with the latest pull request, it is used to copy the typescript type files and thus should be a dev dependency! good catch!

2. Another good catch, this should've been fixed a while ago.... 

I probably won't have time to fix these tonight but I'll fix these for sure! Thanks!
(ps: feel free to put in a PR for this if you can't wait a few hours/ a day)


<br /><br />
_(2: this used to be a module for myself, before I shared it with the world, and this is probably a remnant from that era)_

**Comment by Mastermindzh** [comment]
[Version 2.0](https://www.npmjs.com/package/react-cookie-consent/v/2.0.0) has all the fixes you talked about in it.

Thanks for the PR!
