### ISSUE TITLE
iE11 polyfill

### ISSUE THREAD

**Issue by nikasparmar** [Mastermindzh/react-cookie-consent#34]
when running on IE11 with server side rendering using nextjs Object.assign is not a function error is thrown.would be great if you can add polyfill.

**Comment by Mastermindzh** [comment]
I can do that, check back in about 10-15 mins :)

**Comment by Mastermindzh** [comment]
This bug should be fixed in version [2.0.1](https://www.npmjs.com/package/react-cookie-consent/v/2.0.1).

Please re-open the ticket if the bug hasn't been fixed.

Thanks for the contribution!
