### ISSUE TITLE
acceptOnScroll not being respected in debug mode

### ISSUE THREAD

**Issue by 814k31** [Mastermindzh/react-cookie-consent#39]
The value of acceptOnScroll is ignored in debug mode meaning it always creates the scroll listener

This should fix it:
```diff
-    if ((this.props.acceptOnScroll && Cookies.get(cookieName) === undefined) || debug) {
+    if (this.props.acceptOnScroll && (Cookies.get(cookieName) === undefined || debug)) {
```

**Comment by Mastermindzh** [comment]
Hey Blake,

Are you certain of that?
Can you reproduce it on the [demo site](https://mastermindzh.github.io/react-cookie-consent/)?

If I copy (and paste) the text 20-30 times and scroll down eventually I'll get a popup with "yay" as seen below:

![demo acceptOnScroll](https://i.imgur.com/qUYzi5bg.png)

I can test more thoroughly in the afternoon though (at work now)

**Comment by Mastermindzh** [comment]
Closing due to no response.
