### ISSUE TITLE
v2.4.0 broken npm deploy

### ISSUE THREAD

**Issue by csoLs** [Mastermindzh/react-cookie-consent#50]
`react-cookie-consent@2.4.0` (https://github.com/Mastermindzh/react-cookie-consent/pull/47) was deployed to npm without the last merge commit of that PR. That merge contains updates to the ts file (https://github.com/Mastermindzh/react-cookie-consent/pull/40) so 2.4.0 is missing that bug fix thus breaking any ts project currently on 2.4.0

Fix: Redeploy to npm

Another issue with #47 is this new type definition:
https://github.com/Mastermindzh/react-cookie-consent/pull/47/files?file-filters%5B%5D=.js&file-filters%5B%5D=.ts#diff-b739f95ace6bbf2f0fd5e8cf1dab97d8R20
Should be `setDeclineCookie?: boolean`

**Comment by Mastermindzh** [comment]
I can't blame anyone but myself...

Give me a few mins :)

**Comment by Mastermindzh** [comment]
Fixed in [2.4.1](https://www.npmjs.com/package/react-cookie-consent/v/2.4.1)
