### ISSUE TITLE
customized children accept cookie button

### ISSUE THREAD

**Issue by jvrjosephlouie** [Mastermindzh/react-cookie-consent#53]
Is there a way to add a button element as children of the component, and the function is same as the accept button?

i just want to put the button inside a position relative div while the parent component is still fixed position. 

thanks

**Comment by Mastermindzh** [comment]
I don't think that's "possible" without a significant rewrite of the component.

One of the things you can do (as a workaround) is:
Make the new button click the old one which you promptly hide (e.g invisible button).

This would result in a click on the new button executing the accept function and all related stuff which has been put in the `onAccept()` function.

Best I can come up with I'm afraid.

**Comment by jvrjosephlouie** [comment]
Thank you so much

**Comment by Mastermindzh** [comment]
No problem! Enjoy the component.
I'll mark this as closed now, feel free to re-open if any other help is needed.

Don't forget to star the project to receive update notifications!
