### ISSUE TITLE
Disable button

### ISSUE THREAD

**Issue by CharlotteArai** [Mastermindzh/react-cookie-consent#54]
Hey! 
Thanks for a great package/component!
I just have a quick question - is it possible to somehow disable the button? I want the user to check a checkbox before they can click accept. Any suggestions on how I can achieve this?

Many thanks, 
Charlotte 🤓

**Comment by Mastermindzh** [comment]
There are no native ways (or params) to do this with the package.

Without modifying the package you have a few options though, a combination of all would be the best IMO.

1. Disable the button with JS or CSS (either add "disabled" or style the button to look inactive)
2. Enable the button when the checkbox has been clicked
3. The OnAccept function checks whether the checkbox has been checked. If not, give the user a nice little notice.

This would give the best result IMO.

**Comment by Mastermindzh** [comment]
Closing because of no response.
