### ISSUE TITLE
How center button Accept?

### ISSUE THREAD

**Issue by ssheduardo** [Mastermindzh/react-cookie-consent#55]
How center the button?

![image](https://user-images.githubusercontent.com/1160138/70245624-b21c4b80-1776-11ea-92e9-f711730151dd.png)

**Comment by Mastermindzh** [comment]
Here you go my friend:


```
location="bottom"
buttonText="Sure man!!"
style={{ background: "#2B373B", justifyContent: "center" }}
buttonStyle={{ marginTop: "0px" }}
contentStyle={{flex: "0 0 100%", textAlign: "center"}}
```
gives:
![issue55](https://user-images.githubusercontent.com/4190290/70262081-f5d17e00-1793-11ea-9b4f-cfac6dcaf4c4.png)


Stackblitz: https://stackblitz.com/edit/react-cookie-consent-decline-button-demo-center-button

**Comment by Mastermindzh** [comment]
Closing because of no response.

**Comment by AdeJulius46** [comment]
Thanks so much for this helped me year 2024 😂
