### ISSUE TITLE
onDecline disable Google tag manager

### ISSUE THREAD

**Issue by AskatDzhambulov** [Mastermindzh/react-cookie-consent#58]
Hey!
I`m using gatsby-plugin-google-tagmanager plugin. When page open it`s automaticly set this google tag manager to cookies. But how can i  disable google tag manager with onDecline function and don`t set it in cookies ?

**Comment by Mastermindzh** [comment]
You can't use onDecline to prevent the cookie being set unless you can somehow force the google tag manager to wait until the user has clicked either button.

What you can do, is remove the cookie that GoogleTagManager has set with:

```js
Cookies.remove
```

A [stackblitz](https://stackblitz.com/edit/react-cookie-consent-decline-button-demo-f362sc) which shows an example of this

**Comment by AskatDzhambulov** [comment]
Thanks!
