### ISSUE TITLE
How to trigger react-cookie-consent on click of a link/button?

### ISSUE THREAD

**Issue by ajmalafif** [Mastermindzh/react-cookie-consent#59]
I am trying to replicate this behavior which on clicking say a link or button; it reopens react-cookie-consent so if non-technical visitor changed their minds they can do it without having to clear cookie with devtools:

![framer](https://user-images.githubusercontent.com/827167/73365709-aa48d580-42e7-11ea-8296-cb60074362ec.gif)

**Comment by Mastermindzh** [comment]
This can be done like so:

- render the Cookiebar based on state values
- Let the button remove the cookie (so the bar will render)
- Let the button toggle the state value to trigger an immediate re-render

I made a [stackblitz](https://stackblitz.com/edit/react-cookie-consent-re-open) confirming this works.

**Comment by ajmalafif** [comment]
Thank you @Mastermindzh! Really appreciate to know and thanks for assuring it's possible! 

I'll be honest right now that's above my head to implement, as I learned how to use your repo from this tutorial: https://www.improvebadcode.com/gatsby-gdpr-cookie-consent/

I'll figure out how to make it work and will share the learning here. Feel free to close the issue for now!
