### ISSUE TITLE
Google Analytics is not activated

### ISSUE THREAD

**Issue by emrecan-s** [Mastermindzh/react-cookie-consent#61]
Hi,
In order to see the user data, the user needs to refresh the page after accepting the cookie consent. Even after navigating to a new page the Google Analytics is not activated.

I am using gatsby with gatsby-gdpr-google-analytics

```
import CookieConsent from 'react-cookie-consent';

<CookieConsent
          location="bottom"
          buttonText="Accept"
          declineButtonText="Decline"
          cookieName="gatsby-gdpr-google-analytics">
... check out our Privacy Policy.
</CookieConsent>```

**Comment by Mastermindzh** [comment]
On the [gatsby-plugin-gdpr-cookies](https://www.gatsbyjs.org/packages/gatsby-plugin-gdpr-cookies/) page I see a "anonymize" section which offers an opt-out. You could execute this when the user clicks the decline button.

An example:

`<CookieConsent onDecline={() => {gaOptout();}}></CookieConsent>`

I have no experience with this gatsby plugin so I can't really help you any further.

**Comment by emrecan-s** [comment]
Hi, I tried it but not working, also I don't have any decline button on the site. There is only an accept button visible.

**Comment by Mastermindzh** [comment]
Add `enableDeclineButton` to your CookieConsent code:

```
<CookieConsent
	enableDeclineButton
    location="bottom"
    buttonText="Accept"
    declineButtonText="Decline"
    cookieName="gatsby-gdpr-google-analytics">
	onDecline={() => {gaOptout();}}
... check out our Privacy Policy.
</CookieConsent>
```
