### ISSUE TITLE
Add option to override containerClass name entirely

### ISSUE THREAD

**Issue by stephent** [Mastermindzh/react-cookie-consent#64]
The default name of 'cookieConsent', used to style the container div, appears on some ad blocker's "annoyances filter" list, e.g. AdGuard. See the list at https://filters.adtidy.org/extension/chromium/filters/14.txt.

By default, react-cookie-consent will be blocked if this filter is enabled:

![Screenshot_2020-05-06_at_10_51_21](https://user-images.githubusercontent.com/898090/81239621-9a195400-8fc2-11ea-882c-6775de8c14db.png)

It would be useful to have an option to override the containerClass name entirely so as to be able to try to avoid these sort of blocks. If employed, the caller would be responsible for providing replacement styling for the alternative class name given.

This could be useful on sites where acceptance of cookies is required in order for the site to function.

**Comment by Mastermindzh** [comment]
I agree. Thanks for the detailed issue description.
I will roll out an update this weekend which addresses this issue.

**Comment by Mastermindzh** [comment]
I decided to remove the cookieConsent className entirely as it wasn't used for styling anymore. (it might've been in one of the pre-release versions, idk).

Users now have to assign their own classes (same way as before) and style those or style the component using the built-in properties.

Note, I released it as a major version because I also fixed some styling issues (which I consider a breaking change). To fix it on your site please update to version [4.0.0](https://www.npmjs.com/package/react-cookie-consent/v/4.0.0)

Best regards,
Rick

**Comment by stephent** [comment]
Many thanks Rick :) I'll give this a go today.

One thought: might it actually be good to keep the className even if not required for styling? By removing it, it's probably now harder for AdGuard and similar to block the cookie consent form. While that may be generally what we devs would prefer, it may not be what users prefer.

I wonder if playing nice with the filter list by default, but providing an option to dodge it if needed might be the least bad option here?

**Comment by Mastermindzh** [comment]
Perhaps you're right.
I guess I will add CookieConsent as a default value for the containerClasses, this way a developer can overwrite it if they desire but I'm sure most won't.

PS: I'm not too keen on hiding the message from users as I do think users should be aware of cookies. I do not, however, agree with the need for aggressive cookie bars and popups and can imagine a somewhat more technical user wants to avoid them.

**Comment by Mastermindzh** [comment]
Implemented in version [4.1.0](https://www.npmjs.com/package/react-cookie-consent/v/4.1.0)

**Comment by stephent** [comment]
Thanks Rick - so, question, does setting containerClasses now replace the 'cookieConsent' class name? When I tried that my containerClasses were set in addition to 'cookieConsent'. Thanks!

**Comment by Mastermindzh** [comment]
It will now overwrite it, yes. The default value is still cookieConsent but when you specify classes yourself it won't have cookieConsent as a class anymore.
