### ISSUE TITLE
Wrapper for buttons to keep them together

### ISSUE THREAD

**Issue by gregfenton** [Mastermindzh/react-cookie-consent#65]
## The Problem

If rendered on a smaller screen, the wrapping of accept/decline buttons is a problem:

![image](https://user-images.githubusercontent.com/4407559/81325068-d782ed80-9065-11ea-964c-9041a4bdd985.png)

## Reproduction steps
To see the above, simply narrow the browser window, or using Chrome:
1. start Chrome Developer Tools (F12)
1. click Toggle Device Toolbar
1. ensure the Device Toolbar is set to Responive
1. narrow the window until the first button wraps

## A suggestion
Consider adding a wrapper div around the buttons and exposing the class properties for it?

## Possible workaround
I haven't experimented with yet:

1. disabled the decline button
1. pass in your own ButtonComponent property
1. your ButtonComponent would actually render a container and 2 buttons

This puts a lot of burden on the user to render both buttons and maintain properties across them.

**Comment by rawatnaresh** [comment]
I agree with @gregfenton . I wanted to have a wrapper around the buttons so I could align them differently. But there is no way to do that right now. 

1) Let's say I disabled the the decline button and passed a custom `ButtonComponent` property, with a wrapper and 2 buttons inside it,  I wont be able to call any events when the user disagrees with the consent.
2) If i enable both of the buttons then there is no point in passing a custom `ButtonComponent` becauese I'll have two different wrappers (not a single wrapper that wraps both the buttons)

**Comment by Mastermindzh** [comment]
I agree. Buttons should stick together.
I will update it today. Thanks.

**Comment by Mastermindzh** [comment]
Fixed in version [4.0.0](https://www.npmjs.com/package/react-cookie-consent/v/4.0.0).

The default settings keep the buttons together, you can overwrite it by passing classes to the wrapper.

Thanks for the issue, don't forget to star the repo.

Cya :)
