### ISSUE TITLE
Possibibility to set the sameSite attribute of the created cookie

### ISSUE THREAD

**Issue by timur-han** [Mastermindzh/react-cookie-consent#67]
Thank you for the great contribution!
Soon firefox will reject the non-secure cookies with the attribute sameSite set none:

Cookie “myCookie” rejected because it has the “sameSite=none” attribute but is missing the “secure” attribute.

Currently, it is just a warning. Can we have possibility to specify sameSite in the configuration of the component?

**Comment by Mastermindzh** [comment]
Hey Timur,

Thanks for pointing this out to me.
I will watch for PR's or when I have time fix this myself.

**Comment by mding5692** [comment]
Hey @Mastermindzh I can open up a PR addressing the issue, was wondering whats a good way to test and try the component locally? Using example branch?

**Comment by Mastermindzh** [comment]
Very simple actually:

- clone repository in directory "code"
- clone repository again in directory "example"
- `npm install && npm run build` in the code directory
- `npm link` in the code directory
- git checkout examplebranchname (I forget..) in the example repo
- `npm link react-cookie-consent` in the example repo
- `npm start` in the example repo

Now, whenever you trigger a build in the code repo it will refresh in the example repo with the updated code :)

I'll wait for your PR then. If you want you can make a PR ahead of time so I can give you some feedback on code you've already written.

Excited to work with you,
Best regards,
Rick.

**Comment by mding5692** [comment]
Much thanks, will do that!

**Comment by mding5692** [comment]
Hi @Mastermindzh you should be able to review my PR now, much thanks

**Comment by Mastermindzh** [comment]
Seems we forgot to mark this as fixed in our commits! silly us.

Thanks @mding5692 for the issue report and the work to fix it!
See the [pr](https://github.com/Mastermindzh/react-cookie-consent/pull/68) for details.

Fixed in v[5.0.0](https://www.npmjs.com/package/react-cookie-consent/v/5.0.0)
