### ISSUE TITLE
Support overlay when cookie consent component is visible.

### ISSUE THREAD

**Issue by Steague** [Mastermindzh/react-cookie-consent#72]
I have submitted a PR #71 to implement an overlay feature that will cover all of the page with exception of the consent component itself.

Steps to test the feature are included in the PR.

Inspiration for this came from seeing how the cookie consent feature worked on https://imgur.com/

**Comment by Mastermindzh** [comment]
Yes, I saw it :smile: 

Will make for a nice addition to package once merged.

Thanks for the contribution!

**Comment by Mastermindzh** [comment]
Fixed by your PR :smile:
