### ISSUE TITLE
How do I fix CookieConsent-legacy name?

### ISSUE THREAD

**Issue by ajmalafif** [Mastermindzh/react-cookie-consent#73]
I didn‘t update my codebase at all except for dependabot PRs. I‘m noticing either my renamed CookieConsent or default have `-legacy` appended to it. 

I am not sure how to resolve this and right now I‘m resorting to to have `CookieConsent-legacy` in my code. What is the context that triggers this `legacy` appended in the name? 

Thank you! will share a tutorial for beginners like myself once I resolve this.

**Comment by Mastermindzh** [comment]
The short story is that some browsers don't support the SameSite=None attribute.
The modern browsers force you to have SameSite set to something other than none...

So react-cookie-consent fixes this like so:

- set the fallback cookie (e.g -legacy) first, this will always succeed (on both browsers
- set the correct cookie second (this will work on modern browsers, fail on older ones

This happens on lines [186-192](https://github.com/Mastermindzh/react-cookie-consent/blob/master/src/index.js#L186-L192)

When checking the cookie it'll do it in reverse. If the regular cookie exists, it'll use that. If no regular cookie exists it'll check whether the legacy cookie exists. If both don't exist no consent was given.

This happens on lines [200-2010](https://github.com/Mastermindzh/react-cookie-consent/blob/master/src/index.js#L200-L210)


The long story can be found here: [pull-request#68](https://github.com/Mastermindzh/react-cookie-consent/pull/68)

**Comment by ajmalafif** [comment]
Thanks for the context @Mastermindzh 

Mine is a personal site so changing the setting to `SameSite="strict"` fixed it. Thanks again!
