### ISSUE TITLE
Invalid prop style error after overlay release

### ISSUE THREAD

**Issue by mhatvan** [Mastermindzh/react-cookie-consent#74]
After upgrading to v5.1.0, on page load, the following warning appears:
```index.js:2177 Warning: Invalid prop `style` supplied to `React.Fragment`. React.Fragment can only have `key` and `children` props.```

It happens because of this line of code: https://github.com/Mastermindzh/react-cookie-consent/commit/76ec5ba9e6bc2ad411cc2b9e5f0da6b6308245aa#diff-1fdf421c05c1140f6d71444ea2b27638R324

At first I thought it is the custom `style` prop that I pass in, but the error also happens without any props passed to `<CookieConsent/>` from the user.

**Comment by Mastermindzh** [comment]
This is fixed in [5.1.1](https://www.npmjs.com/package/react-cookie-consent/v/5.1.1).

Thanks for the heads-up!

**Comment by mhatvan** [comment]
Great, thank you for the fast fix ;)

**Comment by Mastermindzh** [comment]
No problem man, it was a small fix and I had a bit of time.
