### ISSUE TITLE
Positioning styles passed to component no longer work

### ISSUE THREAD

**Issue by kimroen** [Mastermindzh/react-cookie-consent#75]
Hi!

We used to call the component setting `position: sticky` like this, to make the cookie banner "sticky":

```js
<CookieConsent style={{ position: 'sticky' }}>
  Cookie text!
</CookieConsent>
```

But now that the component has a wrapping div, this style is set on the inner div instead, and the positioning doesn't work.

Is there a new configuration we should be looking at to make this work like it used to? Thanks!

**Comment by Mastermindzh** [comment]
Hey @kimroen ,

Do you have an example of what you want? I'm not too familiar with sticky position.
I tried to find your problem but I couldn't.

**Comment by Mastermindzh** [comment]
I can just fix the wrapper, the current implementation has bugged me for a bit...
Should solve your issue as well... (though I'd still love an example if you have the time)

**Comment by Mastermindzh** [comment]
Should be fixed in [5.1.2](https://www.npmjs.com/package/react-cookie-consent/v/5.1.2).

Please let me know :)

**Comment by kimroen** [comment]
Thanks!

Absolutely, here's a little explanation:

Position `sticky` makes it so that the element stays where it normally would inside the viewport, except when it gets to the edge, it "sticks" there, like it would if it were positioned absolutely relative to the scrolling container.

Here's an example from MDN where the section headers are positioned sticky, so they "stick" to the top of their section.: https://codepen.io/simevidas/pen/JbdJRZ

In our case, we have a footer at the bottom of the page, and we want the user to be able to scroll to the footer even though the cookie overlay should be overlaying the content at all other times.

Here's our site from before we posted this github issue (note how you can scroll to the footer):

https://voisey-website-2p9xz5c6e.vercel.app/

And here's the site after the update (where the cookie notice is below the content entirely because our positioning css isn't applied):

https://voisey-website-a1epegpd0.vercel.app/

Hope that clears it up!

**Comment by kimroen** [comment]
@Mastermindzh Thanks, this now works as expected! ✨

**Comment by Mastermindzh** [comment]
Cool, not great with css myself.
Glad it fixed it!
