### ISSUE TITLE
react-cookie-consent storing data twice on click

### ISSUE THREAD

**Issue by AbdulAhad125** [Mastermindzh/react-cookie-consent#77]
Hey i am using this npm package https://www.npmjs.com/package/react-cookie-consent for creating a cookies consent in my react type script app now and through this package i can store some data in cookies after user permission. Now there are two problems first it is storing after clicking on accept button it stores two object in cookies, second the change in cookies is not showing immediately in application tab in cookies section i had to reload to see the changes.

```

import React, {FC} from 'react'
import CookieConsent from "react-cookie-consent";

const CookiesBar : FC<any> = ({closeCookieBar}) => {
  const lang = localStorage.getItem('language');
  return (
    <CookieConsent
      location="bottom"
      enableDeclineButton
      buttonText="I understand"
      declineButtonText="Decline"
      style={{ background: "#2B373B" }}
      cookieName="language"
      cookieValue={`${lang}`}
      buttonStyle={{ color: "#4e503b", fontSize: "13px" }}
      declineButtonStyle={{ fontSize: "13px" }}
      setDeclineCookie={false}
      onAccept={({ acceptedByScrolling }) => {
        if (!acceptedByScrolling) {
          closeCookieBar();
        }
      }}
      onDecline={() => closeCookieBar()}
    >
      This website uses cookies to enhance the user experience.{" "}
    </CookieConsent>
  )
}
export default CookiesBar;

```

**Comment by AbdulAhad125** [comment]
@Mastermindzh

**Comment by Mastermindzh** [comment]
The reload on the cookie tab is normal. That is a browser thing. The cookie is available instantly but the UI just doesn't refresh on its own.

It setting two cookies is also perfectly normal. One of them is named "legacy" because some browsers can't read the first cookie because of the same-site settings. See issue for more details. I will add an explanation to the readme so others are aware as well.

**Comment by AbdulAhad125** [comment]
It save two cookies of same name in my case 'language'

**Comment by Mastermindzh** [comment]
Can you provide a stackblitz or some code?

**Comment by AbdulAhad125** [comment]
> Can you provide a stackblitz or some more code?

It worked thanks now 2 cookies are storing 1 is which. i am storing an other with legacy. Any ways thanks for replies @Mastermindzh

**Comment by Mastermindzh** [comment]
No problem, glad it's resolved.
