### ISSUE TITLE
Check if the cookie exists

### ISSUE THREAD

**Issue by rodrigo-arias** [Mastermindzh/react-cookie-consent#78]
Hi Rick,

Great job with this plugin. I'm trying to add a class to the body to add a margin at the bottom so that the cookie is not displayed over the footer.

What do you think is the way to check if the cookie was accepted? Not only in `onAccept` but even if it was previously accepted.

Should I just use `document.cookie`?

Thanks

**Comment by Mastermindzh** [comment]
I.m.o you should import Cookies (from js-cookie) and use that:

```js
import CookieConsent, { Cookies } from "react-cookie-consent"


if(Cookies.get("name")){
logic...
}
```

**Comment by rodrigo-arias** [comment]
Thanks for the quick reply, that was what I was looking for and it works fine.
