### ISSUE TITLE
buttonWrapperClasses type missing.

### ISSUE THREAD

**Issue by tommaton** [Mastermindzh/react-cookie-consent#79]
The type `buttonWrapperClasses` is missing therefore throwing a typescript error even though it still applies the custom class to the button wrapper

![Screenshot 2020-07-16 at 23 05 50](https://user-images.githubusercontent.com/3616123/87727523-04b3f080-c7b9-11ea-9057-4f2092a3fde5.png)

![Screenshot 2020-07-16 at 23 06 03](https://user-images.githubusercontent.com/3616123/87727471-eea63000-c7b8-11ea-8c35-86e2a133ea58.png)

**Comment by Mastermindzh** [comment]
Sorry for the late reply :)

As you can see mastacheata already fixed it so I will merge that stuff tomorrow.
