### ISSUE TITLE
Tag releases, Link in Changelog, Add Dates to Changelog

### ISSUE THREAD

**Issue by mastacheata** [Mastermindzh/react-cookie-consent#81]
Hey there,

I'd like to suggest a few organisational changes to your change handling:

1.  Please tag releases => That way visitors from the outside can have a look at what changed in versions by themselves and see how/why you changed what's mentioned in the changelog. If it's too much work to go through history and tag all releases, maybe just start with it now. (At least future me can profit that way 😄)
2.  Building on top of that, you could then link said tags in the changelog and have a coarse overview in the Changelog.md and a more fine-grained/detailed change view from the Github history.
3.  Add dates to the version numbers (This would also help with 1.)

This is obviously only a personal preference and doing so for past releases might be a lot more work than neccessary, I'd be more than happy if you'd just consider this for the future at least.

Thanks

**Comment by Mastermindzh** [comment]
1. Can do. Just need to remember it.
2. I kinda like having it all in the changelog, if I ever move the repo all changes are still in "code".
3. For versioning I tend to follow [semver](https://semver.org/), but I could add dates on the tags/changelog.

I'll take it into account for the next release (with your PR) and try (but can't make promises...) to do it in the future if it helps others. No big deal to add some tags/dates anyway.

Sound good :D?

**Comment by mastacheata** [comment]
Cool, thanks for taking my suggestion into account.
Again, I'm not here to dictate how you should run your project, it's just a suggestion.

I think you misunderstood my idea for 2., though. I didn't mean to change anything about what you write in the changelog. This was more an idea for linking the fine grained (i.e. code)-changes via the tags, but I guess that's more complicated as you'd have to adjust the changelog after the fact, so maybe this item isn't really a good suggestion unless it's automated. 🤷

**Comment by Mastermindzh** [comment]
Automation is a pain on Github to be frank.

This project is too small to set up propper CI/CD through jenkins/circleci or whatnot and I **really** dislike actions compared to the other options out there (f.e bitbucket's excellent pipelines)

No problem, I welcome the suggestions :)

**Comment by Mastermindzh** [comment]
Tagged and released the latest version with your squashed PR as the entry commit. Future tags will include the build step as well.

Also added some configs to do it automatically because otherwise, I'll end up forgetting for sure...

Changelog also links to the release (because the URL is predictable). So now you have:

1. Tags are being created. Releases are being created.
2. The changelog points to the correct release (predictable URI) (release points to a tag, which points to commits... etc. fine-grained control)
3. I decided against dates in the tag because it would complicate matters too much imo. I forgot the date in the changelog... but I don't mind adding them there.

Please inspect the stuff I did and be sure to let me know if you have additional tips :)

**Comment by mastacheata** [comment]
> 1.   Tags are being created. Releases are being created.

🎉 Thank you very much. I like this a lot.

> 2.  The changelog points to the correct release (predictable URI) (release points to a tag, which points to commits... etc. fine-grained control)

Cool, yeah that's what I meant 👍 

> 3.   I decided against dates in the tag because it would complicate matters too much imo. I forgot the date in the changelog... but I don't mind adding them there.

That's fine with me as well. If I ever need to look up when some change happened, I can now just look at the tags/releases page,

Thank you again for taking your time to implement all of this.
