### ISSUE TITLE
Issue in Chrome console: Mark cross-site cookies as Secure to allow setting them in cross-site contexts

### ISSUE THREAD

**Issue by Devalo** [Mastermindzh/react-cookie-consent#82]
The warning reads:
Cookies marked with SameSite=None must also be marked with Secure to allow setting them in a cross-site context. This behavior protects user data from being sent over an insecure connection.

Resolve this issue by updating the attributes of the cookie:
Specify SameSite=None and Secure if the cookie is intended to be set in cross-site contexts. Note that only cookies sent over HTTPS may use the Secure attribute.
Specify SameSite=Strict or SameSite=Lax if the cookie should not be set by cross-site requests

**Comment by Devalo** [comment]
It may look like this only happens on a local dev server. When I tried it on a prod server over https, the warning seems to go away

**Comment by Mastermindzh** [comment]
That is correct. As the warning suggest the combination can only be used on TLS secured connections.
Please refer to either [pr 68](https://github.com/Mastermindzh/react-cookie-consent/pull/68) or [issue 67](https://github.com/Mastermindzh/react-cookie-consent/issues/67) for more details :)
