### ISSUE TITLE
Cookie is lost in translation, whilst using iOS Chrome & Android Firefox

### ISSUE THREAD

**Issue by Mortuie** [Mastermindzh/react-cookie-consent#83]
We are currently using your cookie consent banner in production and noticed a bug. 

We used all default values except that we used ```sameSite="strict"```. However when testing our banner we noticed that when we login and log out using (aws cognito) the cookie just disappears from the cookie storage on Apple iOS chrome (mobile) & Android Firefox releases. This problem disappears when we change ```sameSite="lax"``` 

Anyone have any explanations as to why this is happening?

**Comment by Mastermindzh** [comment]
I have no clue. Never used AWS cognito either.
React-cookie-consent only sets the cookie, it never removes it.

Do you think you can set up an example in pastebin where it happens? I could set up AWS cognito if required..
