### ISSUE TITLE
Cookie not set in Chrome

### ISSUE THREAD

**Issue by cristian-eriomenco** [Mastermindzh/react-cookie-consent#84]
Hi i'm using Chrome Version 85.0.4183.121 (Official Build) (64-bit) on Windows 10 x64

After accepting the cookie is not set.

If testing on Edge, Firefox , everything works as expected. Could somebody please attempt to test on same version thanks.

**Comment by JeromeGillard** [comment]
This is a new Chrome 85 feature: "Reject insecure SameSite=None cookies".  
(source https://developers.google.com/web/updates/2020/07/chrome-85-deps-rems).

Workaround is to set the `sameSite` attribute to something else than `none`.

**Comment by Mastermindzh** [comment]
True. Full details available here:
https://github.com/Mastermindzh/react-cookie-consent/pull/68

I could make the default option "lax", would have to look at what implications that has.
Any ideas from the two of you? :)

**Comment by cristian-eriomenco** [comment]
@JeromeGillard @Mastermindzh Thank you both for fast reply. After learning a bit more about same site policy. It seems that most resources point to default value being Lax, as its a compromise between none and same-site. And for the nature of functionality the plugin provides i think it makes sense to use lax as default value..

**Comment by Mastermindzh** [comment]
Ok, that's what I was leaning towards. I'll make it so ;)

**Comment by Mastermindzh** [comment]
It's set to LAX in [5.1.4](https://www.npmjs.com/package/react-cookie-consent/v/5.1.4)

Enjoy :)
