### ISSUE TITLE
Is there a way to use a single button for opting out? Like using it as a component for on my privacy policy page..

### ISSUE THREAD

**Issue by mikeyfe6** [Mastermindzh/react-cookie-consent#87]

**Comment by Mastermindzh** [comment]
There are 2 main ways to do this:

1. Hide the Accept button (you can pass it classes/css, f.e display: none;) and use the decline button.
2. Use the accept button as a decline button, you can style it and give it custom text.

**Comment by Mastermindzh** [comment]
Well no problem! Enjoy!

**Comment by mikeyfe6** [comment]
@Mastermindzh thanks again mast, unfortunately I was looking for a button outside the consentbanner that interacts with it. But I think I have to hardcode it.
