### ISSUE TITLE
Cookie Law Update - Scrolling is no longer to be considered an explicit consent

### ISSUE THREAD

**Issue by poteirard** [Mastermindzh/react-cookie-consent#88]
I saw in a similar package that "accept on scroll" is no longer accepted for GDPR.

See: https://github.com/buildo/react-cookie-banner/issues/68

**Comment by Mastermindzh** [comment]
Thank you. Just as a reference I'd like to add:

[Updated cookie law](edpb.europa.eu/sites/edpb/files/files/file1/edpb_guidelines_202005_consent_en.pdf):

>actions such as scrolling or swiping through a webpage or similar user activity will not under any circumstances satisfy the requirement of a clear and affirmative action: such actions may be difficult to distinguish from other activity or interaction by a user and therefore determining that an unambiguous consent has been obtained will also not be possible. Furthermore, in such a case, it will be difficult to provide a way for the user to withdraw consent in a manner that is as easy as granting it.

**Comment by Mastermindzh** [comment]
Removed in [6.0.0](https://www.npmjs.com/package/react-cookie-consent/v/6.0.0)

Thanks again :)
