### ISSUE TITLE
Suggestion: Use babel-plugin-typescript-to-proptypes

### ISSUE THREAD

**Issue by poteirard** [Mastermindzh/react-cookie-consent#90]
I saw there are all the prop types defined to match the typescript interface. 

Since we are using babel I though we could use https://github.com/milesj/babel-plugin-typescript-to-proptypes 

Thoughts?

**Comment by Mastermindzh** [comment]
The cookie-consent module itself doesn't use any typescript ;)
We only have a type declaration :)

**Comment by poteirard** [comment]
Sure, then I change my suggestion :) Why we don't use just TS and we transpile it with [tsdx](https://github.com/jaredpalmer/tsdx)?

**Comment by Mastermindzh** [comment]
Something to think about indeed, wouldn't give too much benefit seeing as this is so small :)
Let's merge the other prs first.

Thanks for being so active :smile:

**Comment by poteirard** [comment]
Glad to help OSS on Sundays at least 😊

**Comment by Mastermindzh** [comment]
Yeah, used to use my weekends for it as well! Busy working on my house now.
But! tsdx is new for me, and it looks pretty good for smaller setups.

Anyway, I'm off now, good luck today!

**Comment by poteirard** [comment]
I used it for a big monorepo we have in our company with about 30 libraries and it works like a charm out of the box.

**Comment by Mastermindzh** [comment]
More people want a typescript version.
I'll convert from JS -> TS this weekend.

**Comment by Mastermindzh** [comment]
Version [8.0.1](https://www.npmjs.com/package/react-cookie-consent/v/8.0.1) has been released and that feature full typescript support 😄 

The [demo page](https://mastermindzh.github.io/react-cookie-consent/) has been replaced with a storybook version as well.

Enjoy!
