### ISSUE TITLE
[Question] Decline third parties from a third party?

### ISSUE THREAD

**Issue by PlopTheReal** [Mastermindzh/react-cookie-consent#97]
Hey,
Sorry if that's a dumb question but I'm not sure what to do regarding my scenario.

I have a website that integrate stripe payment (an iframe got injected onto the page and a bunch of cookies from stripe are added)
https://stripe.com/cookies-policy/legal

Basically I would like to let the user able to decline the cookies (of course) but also let him able to decline the third parties cookies only (ie google analytics and co (https://stripe.com/cookies-policy/legal#analytics-cookies), but let stripe cookies as they are supposed to be necessary)
Stripe cookies are stored with the url https://js.stripe.com and there are a bunch of third parties.
How likely you guys would do such thing (if that at least make sense)

Many thanks!

**Comment by Mastermindzh** [comment]
To block cookies in an iframe you can run it sandboxed:

```html
<iframe sandbox="allow-scripts" />
```

If you only want to have the stripe cookies simply don't sandbox that iframe.


If I were to offer the functionality I would make it very clear to the user that **some** cookies will still be set even if the user denies to offer payment through (in this case) stripe. I would add a third button which says. "Disable all cookies and payment possibilities."
